server:
   port: 9090


spring:
  application:
    name: emlakburada-gateway
  cloud:
    gateway:
      routes:
      - id: emlakburada
        uri: lb://emlakburada
        predicates:             
        - Path=/adverts/**, /users/**
        - Method=POST,GET
      - id: emlakburada-banner
        uri: http://localhost:8081 
        predicates:
        - Path=/banners/**
        - Method=POST,GET 

eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.cloud.gateway: TRACE

management.endpoints.web.exposure.include: '*'