server:
   port: 9090

spring:
  application:
    name: emlakburada-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8082/auth
  cloud:
    gateway:
      routes:
      - id: emlakburada
        uri: lb://emlakburada
        predicates:             
        - Path=/adverts/**, /users/**
      - id: emlakburada-banner
        uri: http://localhost:8081 
        predicates:
        - Path=/banners/**
        - Method=POST,GET
      - id: emlakburada-auth
        uri: http://localhost:8082
        predicates:
        - Path=/auth/**
        - Method=POST

  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    '[org.springframework.security]': TRACE
